### ISSUE TITLE
Bug s3.path-style-access Error When Changing Integration from MiniO to Oracle OCI Object Storage

### ISSUE THREAD

**Issue by agentelinux** [tabular-io/iceberg-rest-image#125]
Hi Guys,

I am using the configuration with MiniO, and everything works fine. However, when I change the storage to Oracle OCI Object Storage, the integration returns an error.

Temporary Workaround (Unusual Solution):
I discovered a workaround that involves using a new image fixture:

https://hub.docker.com/r/apache/iceberg-rest-fixture
(not found git source)

Steps to Reproduce:

Configure the integration with MiniO.
Switch to Oracle OCI Object Storage.
Observe the error during the integration process.

Expected Behavior:
The integration should work seamlessly when switching to Oracle OCI Object Storage.

Actual Behavior:
An error occurs when attempting to use Oracle OCI Object Storage.

Environment Details:

Software Version: [Specify the version]
Storage Provider: MiniO / Oracle OCI Object Storage
Additional Configuration: required s3.path-style-access=true

Very thanks

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <bucket-name.my-namespace.compat.objectstorage.my-region.oraclecloud.com> doesn't match any of the subject alternative names: [swiftobjectstorage.my-region.oraclecloud.com]
        at org.apache.iceberg.aws.shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
        at org.apache.iceberg.aws.shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
```

**Comment by agentelinux** [comment]
Repository origin:
https://github.com/apache/iceberg/commits/main/docker/iceberg-rest-fixture
